services:
  calculator-db:
    container_name: calculator-pg
    image: postgres:16.2
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 10s
      retries: 5